---
apiVersion: v1
kind: Secret
metadata:
  name: trainbook-secrets
type: Opaque
data:
  DB_URL: bW9uZ29kYitzcnY6Ly9yZXNlcnZhdGlvbkFkbWluOk1BTkFHRVJAZ29kZnJleS1kYi1jbHVzdGVyLmNpdHdmNW4ubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUdvZGZyZXktREItQ2x1c3Rlcg==
  DB_NAME: cmVzZXJ2YXRpb24=  # 'reservation' encoded in base64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainbook-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainbook-app
  template:
    metadata:
      labels:
        app: trainbook-app
    spec:
      containers:
      - name: trainbook-app
        image: godfrey22152/trainbooking-app:latest
      imagePullSecrets:
      - name: regcred  # Secret to pull image from private registry
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: trainbook-secrets
              key: DB_URL
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: trainbook-secrets
              key: DB_NAME
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: trainbook-service
spec:
  selector:
    app: trainbook-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32100
